version: '3'
services:
        web:
                image: nginx
                labels:
                        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
                container_name: nginx
                restart: unless-stopped
                ports:
                        - "80:80"
                        - "443:443"
                volumes:
                        - ./hosts:/etc/nginx/conf.d
                        - ./certs:/etc/nginx/certs
                        - ./html:/usr/share/nginx/html
